<%@ Page Title="Notes" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Notes.aspx.cs" Inherits="Notes" %>

<script runat="server">

</script>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <h1>Notes</h1>
    <p>
        <asp:GridView ID="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="NoteId,LeadId" DataSourceID="SqlDataSourceNotes" AutoGenerateDeleteButton="True" CellPadding="4" ForeColor="#333333" GridLines="None">
            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
            <Columns>
                <asp:BoundField DataField="NoteId" HeaderText="NoteId" InsertVisible="False" ReadOnly="True" SortExpression="NoteId" />
                <asp:BoundField DataField="StateId" HeaderText="StateId" SortExpression="StateId" />
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                <asp:BoundField DataField="Note" HeaderText="Note" SortExpression="Note" />
                <asp:BoundField DataField="DateAdded" HeaderText="DateAdded" SortExpression="DateAdded" ReadOnly="True" />
                <asp:BoundField DataField="LeadId" HeaderText="LeadId" InsertVisible="False" ReadOnly="True" SortExpression="LeadId" />
            </Columns>
            <EditRowStyle BackColor="#999999" />
            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#E9E7E2" />
            <SortedAscendingHeaderStyle BackColor="#506C8C" />
            <SortedDescendingCellStyle BackColor="#FFFDF8" />
            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSourceNotes" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionStringLeadBase %>" SelectCommand="SELECT Notes.NoteId, Notes.StateId, Leads.Name, Notes.Note, CONVERT (nvarchar(10), Notes.DateAdded, 103) as 'DateAdded', Leads.LeadId FROM Notes INNER JOIN Leads ON Notes.LeadId = Leads.LeadId WHERE (Leads.LeadId= @LeadId) ORDER BY Notes.DateAdded DESC"
            DeleteCommand="DELETE FROM [Notes] WHERE [NoteId] = @NoteId">
            <DeleteParameters>
                <asp:Parameter Name="LeadId" Type="Int32" />
            </DeleteParameters>
            <SelectParameters>
                <asp:QueryStringParameter Name="LeadId" QueryStringField="leadId" />
            </SelectParameters>
        </asp:SqlDataSource>
    </p>
    <p>
        <asp:FormView ID="FormView1" runat="server" DataKeyNames="NoteId" DataSourceID="SqlDataSourceNotesForm" DefaultMode="Insert">
            <EditItemTemplate>
                <table class="auto-style1" cellpadding="5">
                    <tr>
                        <td class="auto-style2">Note Id:</td>
                        <td>
                            <asp:Label ID="NoteIdLabel1" runat="server" Text='<%# Eval("NoteId") %>' />
                        </td>
                        <td class="auto-style2">DateAdded:</td>
                        <td>
                            <asp:TextBox ID="DateAddedTextBox" runat="server" Text='<%# Bind("DateAdded", "{0:d}") %>' TabIndex="2" />
                            <ajaxToolkit:CalendarExtender ID="DateAddedTextBox_CalendarExtender" runat="server" Enabled="True" TargetControlID="DateAddedTextBox" TodaysDateFormat="d,MM,yyyy">
                            </ajaxToolkit:CalendarExtender>
                        </td>
                    </tr>
                    <tr>
                        <td class="auto-style2">LeadId:</td>
                        <td>
                            <asp:DropDownList ID="DropDownList1" runat="server" DataSourceID="SqlDataSourceLeads" DataTextField="Name" DataValueField="LeadId" SelectedValue='<%# Bind("LeadId") %>' Visible="False">
                            </asp:DropDownList>
                        </td>
                        <td class="auto-style2">StateId:</td>
                        <td>
                            <asp:DropDownList ID="DropDownList2" runat="server" DataSourceID="SqlDataSourceStatus" DataTextField="Name" DataValueField="StateId" SelectedValue='<%# Bind("StateId") %>' TabIndex="3">
                            </asp:DropDownList>
                        </td>
                    </tr>
                    <tr>
                        <td class="auto-style2">UserId: </td>
                        <td>
                            <asp:DropDownList ID="DropDownList3" runat="server" DataSourceID="SqlDataSourceLeadBaseUsers" DataTextField="Name" DataValueField="UserId" SelectedValue='<%# Bind("UserId") %>' TabIndex="1">
                            </asp:DropDownList>
                        </td>
                        <td class="auto-style2">Note:</td>
                        <td>
                            <asp:TextBox ID="NoteTextBox" runat="server" Text='<%# Bind("Note") %>' TextMode="MultiLine" TabIndex="4" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <asp:Button ID="UpdateButton" runat="server" CausesValidation="True" CommandName="Update" Text="Update" TabIndex="5" />
                        </td>
                        <td>&nbsp;</td>
                        <td>
                            <asp:Button ID="UpdateCancelButton" runat="server" CausesValidation="False" CommandName="Cancel" Text="Cancel" TabIndex="6" />
                        </td>
                        <td>&nbsp;</td>
                    </tr>
                </table>
            </EditItemTemplate>
            <InsertItemTemplate>
                <table class="auto-style1" cellpadding="5">
                    <tr>
                        <td class="auto-style2">Lead Id:</td>
                        <td>
                            <asp:DropDownList ID="DropDownList1" runat="server" DataSourceID="SqlDataSourceLeads" DataTextField="Name" DataValueField="LeadId" SelectedValue='<%# Bind("LeadId") %>' OnDataBound="DropDownList1_DataBound">
                            </asp:DropDownList>
                        </td>
                        <td class="auto-style2">Date Added: </td>
                        <td>
                            <asp:TextBox ID="DateAddedTextBox" runat="server" Text='<%# Bind("DateAdded", "{0:d}") %>' />
                            <ajaxToolkit:CalendarExtender ID="DateAddedTextBox_CalendarExtender" runat="server" Enabled="True" TargetControlID="DateAddedTextBox" TodaysDateFormat="d/MM/yyyy">
                            </ajaxToolkit:CalendarExtender>
                        </td>
                    </tr>
                    <tr>
                        <td class="auto-style2">Status:</td>
                        <td>
                            <asp:DropDownList ID="DropDownList2" runat="server" DataSourceID="SqlDataSourceStatus" DataTextField="Name" DataValueField="StateId" SelectedValue='<%# Bind("StateId") %>'>
                            </asp:DropDownList>
                        </td>
                        <td class="auto-style2">Note:</td>
                        <td>
                            <asp:TextBox ID="NoteTextBox" runat="server" Text='<%# Bind("Note") %>' TextMode="MultiLine" />
                        </td>
                    </tr>
                    <tr>
                        <td class="auto-style2">Introducer:</td>
                        <td>
                            <asp:DropDownList ID="DropDownList3" runat="server" DataSourceID="SqlDataSourceLeadBaseUsers" DataTextField="Name" DataValueField="UserId" SelectedValue='<%# Bind("UserId") %>'>
                            </asp:DropDownList>
                        </td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td>
                            <asp:Button ID="InsertButton" runat="server" CausesValidation="True" CommandName="Insert" Text="Insert" />
                        </td>
                        <td>&nbsp;</td>
                        <td>
                            <asp:Button ID="InsertCancelButton" runat="server" CausesValidation="False" CommandName="Cancel" Text="Cancel" />
                        </td>
                        <td>&nbsp;</td>
                    </tr>
                </table>
            </InsertItemTemplate>
            <ItemTemplate>
                <br />
                <table class="auto-style1" cellpadding="5">
                    <tr>
                        <td class="auto-style2">NoteId:</td>
                        <td>
                            <asp:Label ID="NoteIdLabel" runat="server" Text='<%# Eval("NoteId") %>' />
                        </td>
                        <td class="auto-style2">DateAdded:</td>
                        <td>
                            <asp:Label ID="DateAddedLabel" runat="server" Text='<%# Bind("DateAdded", "{0:d}") %>' />
                        </td>
                    </tr>
                    <tr>
                        <td class="auto-style2">LeadId:</td>
                        <td>
                            <asp:Label ID="LeadIdLabel" runat="server" Text='<%# Bind("LeadId") %>' />
                        </td>
                        <td class="auto-style2">StateId:</td>
                        <td>
                            <asp:Label ID="StateIdLabel" runat="server" Text='<%# Bind("StateId") %>' />
                        </td>
                    </tr>
                    <tr>
                        <td class="auto-style2">Note:</td>
                        <td>
                            <asp:Label ID="NoteLabel" runat="server" Text='<%# Bind("Note") %>' />
                        </td>
                        <td class="auto-style2">UserId:</td>
                        <td>
                            <asp:Label ID="UserIdLabel" runat="server" Text='<%# Bind("UserId") %>' />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <asp:Button ID="EditButton" runat="server" CausesValidation="False" CommandName="Edit" Text="Edit" />
                        </td>
                        <td style="text-align: center">
                            <asp:Button ID="DeleteButton" runat="server" CausesValidation="False" CommandName="Delete" Text="Delete" />
                        </td>
                        <td style="text-align: center">
                            <asp:Button ID="NewButton" runat="server" CausesValidation="False" CommandName="New" Text="New" />
                        </td>
                        <td>&nbsp;</td>
                    </tr>
                </table>
            </ItemTemplate>
        </asp:FormView>
        <asp:SqlDataSource ID="SqlDataSourceNotesForm" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionStringLeadBase %>" DeleteCommand="DELETE FROM [Notes] WHERE [NoteId] = @NoteId" InsertCommand="INSERT INTO [Notes] ([DateAdded], [LeadId], [StateId], [Note], [UserId]) VALUES (@DateAdded, @LeadId, @StateId, @Note, @UserId)" SelectCommand="SELECT * FROM [Notes] WHERE [LeadId] = @LeadId ORDER BY [DateAdded] DESC " UpdateCommand="UPDATE [Notes] SET [DateAdded] = @DateAdded, [LeadId] = @LeadId, [StateId] = @StateId, [Note] = @Note, [UserId] = @UserId WHERE [NoteId] = @NoteId">
            <DeleteParameters>
                <asp:Parameter Name="NoteId" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter DbType="Date" Name="DateAdded" />
                <asp:Parameter Name="LeadId" Type="Int32" />
                <asp:Parameter Name="StateId" Type="Int32" />
                <asp:Parameter Name="Note" Type="String" />
                <asp:Parameter Name="UserId" Type="Int32" />
            </InsertParameters>
            <SelectParameters>
                <asp:QueryStringParameter Name="LeadId" QueryStringField="LeadId" />
            </SelectParameters>
            <UpdateParameters>
                <asp:Parameter DbType="Date" Name="DateAdded" />
                <asp:Parameter Name="LeadId" Type="Int32" />
                <asp:Parameter Name="StateId" Type="Int32" />
                <asp:Parameter Name="Note" Type="String" />
                <asp:Parameter Name="UserId" Type="Int32" />
                <asp:Parameter Name="NoteId" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <asp:SqlDataSource ID="SqlDataSourceLeads" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionStringLeadBase %>" SelectCommand="SELECT [Name], [LeadId] FROM [Leads] WHERE ([LeadId] = @LeadId)">
            <SelectParameters>
                <asp:QueryStringParameter DefaultValue="1" Name="LeadId" QueryStringField="leadId" Type="Int32" />
            </SelectParameters>
        </asp:SqlDataSource>
        <asp:ScriptManager ID="ScriptManager1" runat="server">
        </asp:ScriptManager>
        <asp:SqlDataSource ID="SqlDataSourceStatus" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionStringLeadBase %>" SelectCommand="SELECT [StateId], [Name] FROM [States]"></asp:SqlDataSource>
        <asp:SqlDataSource ID="SqlDataSourceLeadBaseUsers" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionStringLeadBase %>" SelectCommand="SELECT [Name], [UserId] FROM [LeadBaseUsers]"></asp:SqlDataSource>
    </p>
        <asp:Button ID="backToLeadUrl" runat="server" Text="Back to Lead" TabIndex="7" />
</asp:Content>



